### ISSUE TITLE
Error when doing npm start

### ISSUE THREAD

**Issue by JuvenileLad** [out386/TelegramMirrorBot#128]
I am getting this error when I do `npm start`
>Please see Comment 1 before this.
```
> mirror-bot@2.0.0 start
> npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/juvenile_lad/.npm/_logs/2021-01-06T04_54_30_929Z-debug.log
npm ERR! code 1
npm ERR! path /home/juvenile_lad/aria-telegram-mirror-bot
npm ERR! command failed
npm ERR! command sh -c npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/juvenile_lad/.npm/_logs/2021-01-06T04_54_30_982Z-debug.log
```
This is what the log file _2021-01-06T04_54_30_929Z-debug.log_ says:
```
0 verbose cli [
0 verbose cli   '/usr/bin/node',
0 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'typescript'
0 verbose cli ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/juvenile_lad/aria-telegram-mirror-bot/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/juvenile_lad/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 2ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 6cc45b40c6e0476e
20 timing npm:load Completed in 22ms
21 http fetch GET 304 https://registry.npmjs.org/typescript 1126ms (from cache)
22 timing command:exec Completed in 1182ms
23 verbose stack Error: could not determine executable to run
23 verbose stack     at getBinFromManifest (/usr/lib/node_modules/npm/lib/exec.js:263:23)
23 verbose stack     at exec (/usr/lib/node_modules/npm/lib/exec.js:177:15)
24 verbose cwd /home/juvenile_lad/aria-telegram-mirror-bot
25 verbose Linux 5.4.0-59-generic
26 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "typescript"
27 verbose node v15.5.1
28 verbose npm  v7.3.0
29 error could not determine executable to run
30 verbose exit 1
```

This is what log file 2021-01-06T04_54_30_982Z-debug.log says:

```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 3ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/juvenile_lad/aria-telegram-mirror-bot/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/juvenile_lad/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 13626af19c802c63
20 timing npm:load Completed in 24ms
21 timing command:run-script Completed in 1681ms
22 timing command:start Completed in 1684ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1063:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
24 verbose pkgid mirror-bot@2.0.0
25 verbose cwd /home/juvenile_lad/aria-telegram-mirror-bot
26 verbose Linux 5.4.0-59-generic
27 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
28 verbose node v15.5.1
29 verbose npm  v7.3.0
30 error code 1
31 error path /home/juvenile_lad/aria-telegram-mirror-bot
32 error command failed
33 error command sh -c npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js
34 verbose exit 1
```

**Comment by JuvenileLad** [comment]
to begin with, I got this error when doing ```npm install```

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: eslint@6.8.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.0.1" from the root project
npm ERR!   peer eslint@"*" from @typescript-eslint/experimental-utils@1.13.0
npm ERR!   node_modules/@typescript-eslint/experimental-utils
npm ERR!     @typescript-eslint/experimental-utils@"1.13.0" from @typescript-eslint/eslint-plugin@1.13.0
npm ERR!     node_modules/@typescript-eslint/eslint-plugin
npm ERR!       dev @typescript-eslint/eslint-plugin@"^1.12.0" from the root project
npm ERR!     @typescript-eslint/experimental-utils@"1.13.0" from @typescript-eslint/parser@1.13.0
npm ERR!     node_modules/@typescript-eslint/parser
npm ERR!       dev @typescript-eslint/parser@"^1.12.0" from the root project
npm ERR!       1 more (@typescript-eslint/eslint-plugin)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0" from @typescript-eslint/eslint-plugin@1.13.0
npm ERR! node_modules/@typescript-eslint/eslint-plugin
npm ERR!   dev @typescript-eslint/eslint-plugin@"^1.12.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/juvenile_lad/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/juvenile_lad/.npm/_logs/2021-01-06T05_09_37_608Z-debug.log
```

log file _2021-01-06T05_09_37_608Z-debug.log_ says:
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
1 info using npm@7.3.0
2 info using node@v15.5.1
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/home/juvenile_lad/aria-telegram-mirror-bot/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/juvenile_lad/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 verbose npm-session 5cdd7e254f804661
20 timing npm:load Completed in 21ms
21 timing arborist:ctor Completed in 1ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 40ms
24 timing idealTree:userRequests Completed in 0ms
25 silly idealTree buildDeps
26 silly fetch manifest @types/fs-extra@^7.0.0
27 http fetch GET 304 https://registry.npmjs.org/@types%2ffs-extra 788ms (from cache)
28 silly fetch manifest @types/mime-types@^2.1.0
29 http fetch GET 304 https://registry.npmjs.org/@types%2fmime-types 105ms (from cache)
30 silly fetch manifest @types/node-telegram-bot-api@^0.31.0
31 http fetch GET 304 https://registry.npmjs.org/@types%2fnode-telegram-bot-api 131ms (from cache)
32 silly fetch manifest @types/tar@^4.0.0
33 http fetch GET 304 https://registry.npmjs.org/@types%2ftar 102ms (from cache)
34 silly fetch manifest @types/uuid@^3.4.4
35 http fetch GET 304 https://registry.npmjs.org/@types%2fuuid 113ms (from cache)
36 silly fetch manifest aria2@^3.0.1
37 http fetch GET 304 https://registry.npmjs.org/aria2 1035ms (from cache)
38 silly fetch manifest diskspace@^2.0.0
39 http fetch GET 304 https://registry.npmjs.org/diskspace 100ms (from cache)
40 silly fetch manifest fs-extra@^7.0.0
41 http fetch GET 304 https://registry.npmjs.org/fs-extra 113ms (from cache)
42 silly fetch manifest googleapis@^41.0.1
43 http fetch GET 304 https://registry.npmjs.org/googleapis 117ms (from cache)
44 silly fetch manifest http-range-parse@^1.0.0
45 http fetch GET 304 https://registry.npmjs.org/http-range-parse 1120ms (from cache)
46 silly fetch manifest node-telegram-bot-api@^0.30.0
47 http fetch GET 304 https://registry.npmjs.org/node-telegram-bot-api 117ms (from cache)
48 silly fetch manifest tar@^4.4.4
49 http fetch GET 304 https://registry.npmjs.org/tar 98ms (from cache)
50 silly fetch manifest typescript@^3.5.3
51 http fetch GET 304 https://registry.npmjs.org/typescript 161ms (from cache)
52 silly fetch manifest uuid@^3.3.2
53 http fetch GET 304 https://registry.npmjs.org/uuid 117ms (from cache)
54 silly fetch manifest @typescript-eslint/eslint-plugin@^1.12.0
55 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 146ms (from cache)
56 silly fetch manifest @typescript-eslint/parser@^1.9.0
57 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2fparser 250ms (from cache)
58 silly fetch manifest eslint@^5.0.0
59 http fetch GET 304 https://registry.npmjs.org/eslint 126ms (from cache)
60 silly fetch manifest @typescript-eslint/parser@^1.12.0
61 http fetch GET 200 https://registry.npmjs.org/@typescript-eslint%2fparser 13ms (from cache)
62 silly fetch manifest eslint@^6.0.1
63 http fetch GET 304 https://registry.npmjs.org/eslint 119ms (from cache)
64 silly placeDep ROOT @types/fs-extra@7.0.0 OK for: mirror-bot@2.0.0 want: ^7.0.0
65 silly placeDep ROOT @types/mime-types@2.1.0 OK for: mirror-bot@2.0.0 want: ^2.1.0
66 silly placeDep ROOT @types/node-telegram-bot-api@0.31.1 OK for: mirror-bot@2.0.0 want: ^0.31.0
67 silly placeDep ROOT @types/tar@4.0.4 OK for: mirror-bot@2.0.0 want: ^4.0.0
68 silly placeDep ROOT @types/uuid@3.4.9 OK for: mirror-bot@2.0.0 want: ^3.4.4
69 silly placeDep ROOT @typescript-eslint/eslint-plugin@1.13.0 OK for: mirror-bot@2.0.0 want: ^1.12.0
70 silly placeDep ROOT @typescript-eslint/parser@1.13.0 OK for: @typescript-eslint/eslint-plugin@1.13.0 want: ^1.9.0
71 silly placeDep ROOT eslint@5.16.0 OK for: @typescript-eslint/parser@1.13.0 want: ^5.0.0
72 silly placeDep ROOT aria2@3.0.1 OK for: mirror-bot@2.0.0 want: ^3.0.1
73 silly placeDep ROOT diskspace@2.0.0 OK for: mirror-bot@2.0.0 want: ^2.0.0
74 silly placeDep ROOT eslint@6.8.0 REPLACE for: mirror-bot@2.0.0 want: ^6.0.1
75 silly placeDep ROOT fs-extra@7.0.1 OK for: mirror-bot@2.0.0 want: ^7.0.0
76 silly placeDep ROOT googleapis@41.0.1 OK for: mirror-bot@2.0.0 want: ^41.0.1
77 silly placeDep ROOT http-range-parse@1.0.0 OK for: mirror-bot@2.0.0 want: ^1.0.0
78 silly placeDep ROOT node-telegram-bot-api@0.30.0 OK for: mirror-bot@2.0.0 want: ^0.30.0
79 silly placeDep ROOT tar@4.4.13 OK for: mirror-bot@2.0.0 want: ^4.4.4
80 silly placeDep ROOT typescript@3.9.7 OK for: mirror-bot@2.0.0 want: ^3.5.3
81 silly placeDep ROOT uuid@3.4.0 OK for: mirror-bot@2.0.0 want: ^3.3.2
82 silly fetch manifest @types/node@*
83 silly fetch manifest @types/request@*
84 silly fetch manifest @types/minipass@*
85 silly fetch manifest @typescript-eslint/experimental-utils@1.13.0
86 silly fetch manifest eslint-utils@^1.3.1
87 silly fetch manifest functional-red-black-tree@^1.0.1
88 silly fetch manifest regexpp@^2.0.1
89 silly fetch manifest tsutils@^3.7.0
90 silly fetch manifest @types/eslint-visitor-keys@^1.0.0
91 silly fetch manifest @typescript-eslint/typescript-estree@1.13.0
92 silly fetch manifest eslint-visitor-keys@^1.0.0
93 silly fetch manifest @babel/code-frame@^7.0.0
94 silly fetch manifest ajv@^6.9.1
95 silly fetch manifest chalk@^2.1.0
96 silly fetch manifest cross-spawn@^6.0.5
97 silly fetch manifest debug@^4.0.1
98 silly fetch manifest doctrine@^3.0.0
99 silly fetch manifest eslint-scope@^4.0.3
100 silly fetch manifest espree@^5.0.1
101 silly fetch manifest esquery@^1.0.1
102 silly fetch manifest esutils@^2.0.2
103 silly fetch manifest file-entry-cache@^5.0.1
104 silly fetch manifest glob@^7.1.2
105 silly fetch manifest globals@^11.7.0
106 silly fetch manifest ignore@^4.0.6
107 silly fetch manifest import-fresh@^3.0.0
108 silly fetch manifest imurmurhash@^0.1.4
109 silly fetch manifest inquirer@^6.2.2
110 silly fetch manifest js-yaml@^3.13.0
111 silly fetch manifest json-stable-stringify-without-jsonify@^1.0.1
112 silly fetch manifest levn@^0.3.0
113 silly fetch manifest lodash@^4.17.11
114 silly fetch manifest minimatch@^3.0.4
115 silly fetch manifest mkdirp@^0.5.1
116 silly fetch manifest natural-compare@^1.4.0
117 silly fetch manifest optionator@^0.8.2
118 silly fetch manifest path-is-inside@^1.0.2
119 silly fetch manifest progress@^2.0.0
120 silly fetch manifest semver@^5.5.1
121 silly fetch manifest strip-ansi@^4.0.0
122 silly fetch manifest strip-json-comments@^2.0.1
123 silly fetch manifest table@^5.2.3
124 silly fetch manifest text-table@^0.2.0
125 silly fetch manifest commander@^2.9.0
126 silly fetch manifest node-fetch@^2.1.2
127 silly fetch manifest polygoat@^1.1.4
128 silly fetch manifest ws@^5.1.1
129 silly fetch manifest ajv@^6.10.0
130 silly fetch manifest eslint-scope@^5.0.0
131 silly fetch manifest eslint-utils@^1.4.3
132 silly fetch manifest eslint-visitor-keys@^1.1.0
133 silly fetch manifest espree@^6.1.2
134 silly fetch manifest glob-parent@^5.0.0
135 silly fetch manifest globals@^12.1.0
136 silly fetch manifest inquirer@^7.0.0
137 silly fetch manifest is-glob@^4.0.0
138 silly fetch manifest js-yaml@^3.13.1
139 silly fetch manifest lodash@^4.17.14
140 silly fetch manifest optionator@^0.8.3
141 silly fetch manifest semver@^6.1.2
142 silly fetch manifest strip-ansi@^5.2.0
143 silly fetch manifest strip-json-comments@^3.0.1
144 silly fetch manifest v8-compile-cache@^2.0.3
145 silly fetch manifest graceful-fs@^4.1.2
146 silly fetch manifest jsonfile@^4.0.0
147 silly fetch manifest universalify@^0.1.0
148 silly fetch manifest google-auth-library@^4.0.0
149 silly fetch manifest googleapis-common@^2.0.2
150 silly fetch manifest array.prototype.findindex@^2.0.2
151 silly fetch manifest bl@^1.2.1
152 silly fetch manifest bluebird@^3.5.1
153 silly fetch manifest debug@^3.1.0
154 silly fetch manifest depd@^1.1.1
155 silly fetch manifest eventemitter3@^3.0.0
156 silly fetch manifest file-type@^3.9.0
157 silly fetch manifest mime@^1.6.0
158 silly fetch manifest pump@^2.0.0
159 silly fetch manifest request@^2.83.0
160 silly fetch manifest request-promise@^4.2.2
161 silly fetch manifest chownr@^1.1.1
162 silly fetch manifest fs-minipass@^1.2.5
163 silly fetch manifest minipass@^2.8.6
164 silly fetch manifest minizlib@^1.2.1
165 silly fetch manifest mkdirp@^0.5.0
166 silly fetch manifest safe-buffer@^5.1.2
167 silly fetch manifest yallist@^3.0.3
168 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 401ms (from cache)
169 http fetch GET 304 https://registry.npmjs.org/ajv 470ms (from cache)
170 http fetch GET 304 https://registry.npmjs.org/chalk 825ms (from cache)
171 http fetch GET 304 https://registry.npmjs.org/@types%2frequest 958ms (from cache)
172 http fetch GET 304 https://registry.npmjs.org/eslint-utils 1010ms (from cache)
173 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2fexperimental-utils 1023ms (from cache)
174 http fetch GET 304 https://registry.npmjs.org/@types%2fminipass 1051ms (from cache)
175 http fetch GET 304 https://registry.npmjs.org/regexpp 1044ms (from cache)
176 http fetch GET 304 https://registry.npmjs.org/functional-red-black-tree 1067ms (from cache)
177 http fetch GET 304 https://registry.npmjs.org/tsutils 1109ms (from cache)
178 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2ftypescript-estree 1254ms (from cache)
179 http fetch GET 304 https://registry.npmjs.org/@babel%2fcode-frame 1289ms (from cache)
180 http fetch GET 304 https://registry.npmjs.org/eslint-visitor-keys 1296ms (from cache)
181 http fetch GET 304 https://registry.npmjs.org/@types%2feslint-visitor-keys 1301ms (from cache)
182 http fetch GET 304 https://registry.npmjs.org/cross-spawn 1309ms (from cache)
183 http fetch GET 304 https://registry.npmjs.org/debug 1398ms (from cache)
184 http fetch GET 304 https://registry.npmjs.org/doctrine 1457ms (from cache)
185 http fetch GET 304 https://registry.npmjs.org/eslint-scope 1544ms (from cache)
186 http fetch GET 304 https://registry.npmjs.org/espree 1715ms (from cache)
187 http fetch GET 304 https://registry.npmjs.org/esquery 1972ms (from cache)
188 http fetch GET 304 https://registry.npmjs.org/esutils 2003ms (from cache)
189 http fetch GET 304 https://registry.npmjs.org/file-entry-cache 2061ms (from cache)
190 http fetch GET 304 https://registry.npmjs.org/glob 2100ms (from cache)
191 http fetch GET 304 https://registry.npmjs.org/globals 2136ms (from cache)
192 http fetch GET 304 https://registry.npmjs.org/ignore 2224ms (from cache)
193 http fetch GET 304 https://registry.npmjs.org/import-fresh 2239ms (from cache)
194 http fetch GET 304 https://registry.npmjs.org/imurmurhash 2292ms (from cache)
195 http fetch GET 304 https://registry.npmjs.org/inquirer 2330ms (from cache)
196 http fetch GET 304 https://registry.npmjs.org/js-yaml 2377ms (from cache)
197 http fetch GET 304 https://registry.npmjs.org/json-stable-stringify-without-jsonify 2396ms (from cache)
198 http fetch GET 304 https://registry.npmjs.org/levn 2580ms (from cache)
199 http fetch GET 304 https://registry.npmjs.org/lodash 2670ms (from cache)
200 http fetch GET 304 https://registry.npmjs.org/minimatch 2735ms (from cache)
201 http fetch GET 304 https://registry.npmjs.org/mkdirp 2785ms (from cache)
202 http fetch GET 304 https://registry.npmjs.org/natural-compare 2825ms (from cache)
203 http fetch GET 304 https://registry.npmjs.org/optionator 2923ms (from cache)
204 http fetch GET 304 https://registry.npmjs.org/path-is-inside 2955ms (from cache)
205 http fetch GET 304 https://registry.npmjs.org/progress 2979ms (from cache)
206 http fetch GET 304 https://registry.npmjs.org/semver 2971ms (from cache)
207 http fetch GET 304 https://registry.npmjs.org/strip-ansi 2979ms (from cache)
208 http fetch GET 304 https://registry.npmjs.org/strip-json-comments 3013ms (from cache)
209 http fetch GET 304 https://registry.npmjs.org/table 3043ms (from cache)
210 http fetch GET 304 https://registry.npmjs.org/text-table 3098ms (from cache)
211 http fetch GET 304 https://registry.npmjs.org/commander 3117ms (from cache)
212 http fetch GET 304 https://registry.npmjs.org/node-fetch 3147ms (from cache)
213 http fetch GET 304 https://registry.npmjs.org/ws 3207ms (from cache)
214 http fetch GET 304 https://registry.npmjs.org/ajv 3287ms (from cache)
215 http fetch GET 304 https://registry.npmjs.org/eslint-scope 3397ms (from cache)
216 http fetch GET 304 https://registry.npmjs.org/eslint-utils 3501ms (from cache)
217 http fetch GET 304 https://registry.npmjs.org/eslint-visitor-keys 4085ms (from cache)
218 http fetch GET 304 https://registry.npmjs.org/polygoat 4134ms (from cache)
219 http fetch GET 304 https://registry.npmjs.org/espree 4167ms (from cache)
220 http fetch GET 304 https://registry.npmjs.org/globals 4298ms (from cache)
221 http fetch GET 304 https://registry.npmjs.org/inquirer 4449ms (from cache)
222 http fetch GET 304 https://registry.npmjs.org/glob-parent 4517ms (from cache)
223 http fetch GET 304 https://registry.npmjs.org/is-glob 4597ms (from cache)
224 http fetch GET 304 https://registry.npmjs.org/js-yaml 4622ms (from cache)
225 http fetch GET 304 https://registry.npmjs.org/lodash 4658ms (from cache)
226 http fetch GET 304 https://registry.npmjs.org/optionator 4659ms (from cache)
227 http fetch GET 304 https://registry.npmjs.org/semver 4765ms (from cache)
228 http fetch GET 304 https://registry.npmjs.org/strip-ansi 4829ms (from cache)
229 http fetch GET 304 https://registry.npmjs.org/strip-json-comments 5094ms (from cache)
230 http fetch GET 304 https://registry.npmjs.org/v8-compile-cache 5127ms (from cache)
231 http fetch GET 304 https://registry.npmjs.org/graceful-fs 5148ms (from cache)
232 http fetch GET 304 https://registry.npmjs.org/jsonfile 5197ms (from cache)
233 http fetch GET 304 https://registry.npmjs.org/universalify 5309ms (from cache)
234 http fetch GET 304 https://registry.npmjs.org/google-auth-library 5343ms (from cache)
235 http fetch GET 304 https://registry.npmjs.org/array.prototype.findindex 5400ms (from cache)
236 http fetch GET 304 https://registry.npmjs.org/googleapis-common 5421ms (from cache)
237 http fetch GET 304 https://registry.npmjs.org/bl 5421ms (from cache)
238 http fetch GET 304 https://registry.npmjs.org/bluebird 5434ms (from cache)
239 http fetch GET 304 https://registry.npmjs.org/debug 5451ms (from cache)
240 http fetch GET 304 https://registry.npmjs.org/depd 5471ms (from cache)
241 http fetch GET 304 https://registry.npmjs.org/eventemitter3 5599ms (from cache)
242 http fetch GET 304 https://registry.npmjs.org/file-type 5616ms (from cache)
243 http fetch GET 304 https://registry.npmjs.org/mime 5642ms (from cache)
244 http fetch GET 304 https://registry.npmjs.org/pump 5693ms (from cache)
245 http fetch GET 304 https://registry.npmjs.org/request-promise 5710ms (from cache)
246 http fetch GET 304 https://registry.npmjs.org/request 5722ms (from cache)
247 http fetch GET 304 https://registry.npmjs.org/chownr 5725ms (from cache)
248 http fetch GET 304 https://registry.npmjs.org/fs-minipass 5734ms (from cache)
249 http fetch GET 304 https://registry.npmjs.org/minipass 5746ms (from cache)
250 http fetch GET 304 https://registry.npmjs.org/minizlib 5743ms (from cache)
251 http fetch GET 304 https://registry.npmjs.org/mkdirp 5756ms (from cache)
252 http fetch GET 304 https://registry.npmjs.org/safe-buffer 5779ms (from cache)
253 http fetch GET 304 https://registry.npmjs.org/yallist 5853ms (from cache)
254 timing idealTree:#root Completed in 11319ms
255 silly placeDep ROOT @types/node@14.14.20 OK for: @types/fs-extra@7.0.0 want: *
256 timing idealTree:node_modules/@types/fs-extra Completed in 1ms
257 timing idealTree:node_modules/@types/mime-types Completed in 0ms
258 timing idealTree:node_modules/@types/node Completed in 0ms
259 silly placeDep ROOT @types/request@2.48.5 OK for: @types/node-telegram-bot-api@0.31.1 want: *
260 silly fetch manifest @types/caseless@*
261 silly fetch manifest @types/tough-cookie@*
262 silly fetch manifest form-data@^2.5.0
263 http fetch GET 304 https://registry.npmjs.org/@types%2fcaseless 110ms (from cache)
264 http fetch GET 304 https://registry.npmjs.org/@types%2ftough-cookie 139ms (from cache)
265 http fetch GET 304 https://registry.npmjs.org/form-data 151ms (from cache)
266 timing idealTree:node_modules/@types/node-telegram-bot-api Completed in 156ms
267 silly placeDep ROOT @types/caseless@0.12.2 OK for: @types/request@2.48.5 want: *
268 silly placeDep ROOT @types/tough-cookie@4.0.0 OK for: @types/request@2.48.5 want: *
269 silly placeDep ROOT form-data@2.5.1 OK for: @types/request@2.48.5 want: ^2.5.0
270 silly fetch manifest asynckit@^0.4.0
271 silly fetch manifest combined-stream@^1.0.6
272 silly fetch manifest mime-types@^2.1.12
273 http fetch GET 304 https://registry.npmjs.org/combined-stream 116ms (from cache)
274 http fetch GET 304 https://registry.npmjs.org/mime-types 127ms (from cache)
275 http fetch GET 304 https://registry.npmjs.org/asynckit 133ms (from cache)
276 timing idealTree:node_modules/@types/request Completed in 141ms
277 timing idealTree:node_modules/@types/caseless Completed in 0ms
278 silly placeDep ROOT @types/minipass@2.2.0 OK for: @types/tar@4.0.4 want: *
279 timing idealTree:node_modules/@types/tar Completed in 1ms
280 timing idealTree:node_modules/@types/minipass Completed in 0ms
281 timing idealTree:node_modules/@types/tough-cookie Completed in 0ms
282 timing idealTree:node_modules/@types/uuid Completed in 0ms
283 silly fetch manifest typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta
284 http fetch GET 304 https://registry.npmjs.org/typescript 155ms (from cache)
285 silly placeDep ROOT @typescript-eslint/experimental-utils@1.13.0 OK for: @typescript-eslint/eslint-plugin@1.13.0 want: 1.13.0
286 timing idealTree Completed in 11871ms
287 timing command:install Completed in 11875ms
288 verbose stack Error: unable to resolve dependency tree
288 verbose stack     at Arborist.[failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1061:25)
288 verbose stack     at Arborist.[placeDep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1145:30)
288 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:807:46
288 verbose stack     at Array.map (<anonymous>)
288 verbose stack     at Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:807:8)
288 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
288 verbose stack     at async Promise.all (index 1)
288 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:123:5)
288 verbose stack     at async install (/usr/lib/node_modules/npm/lib/install.js:38:3)
289 verbose cwd /home/juvenile_lad/aria-telegram-mirror-bot
290 verbose Linux 5.4.0-59-generic
291 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
292 verbose node v15.5.1
293 verbose npm  v7.3.0
294 error code ERESOLVE
295 error ERESOLVE unable to resolve dependency tree
296 error
297 error Found: [1meslint[22m@[1m6.8.0[22m[2m[22m
297 error [2mnode_modules/eslint[22m
297 error   [33mdev[39m [1meslint[22m@"[1m^6.0.1[22m" from the root project
297 error   [35mpeer[39m [1meslint[22m@"[1m*[22m" from [1m@typescript-eslint/experimental-utils[22m@[1m1.13.0[22m[2m[22m
297 error   [2mnode_modules/@typescript-eslint/experimental-utils[22m
297 error     [1m@typescript-eslint/experimental-utils[22m@"[1m1.13.0[22m" from [1m@typescript-eslint/eslint-plugin[22m@[1m1.13.0[22m[2m[22m
297 error     [2mnode_modules/@typescript-eslint/eslint-plugin[22m
297 error       [33mdev[39m [1m@typescript-eslint/eslint-plugin[22m@"[1m^1.12.0[22m" from the root project
297 error     [1m@typescript-eslint/experimental-utils[22m@"[1m1.13.0[22m" from [1m@typescript-eslint/parser[22m@[1m1.13.0[22m[2m[22m
297 error     [2mnode_modules/@typescript-eslint/parser[22m
297 error       [33mdev[39m [1m@typescript-eslint/parser[22m@"[1m^1.12.0[22m" from the root project
297 error       1 more (@typescript-eslint/eslint-plugin)
297 error
297 error Could not resolve dependency:
297 error [35mpeer[39m [1meslint[22m@"[1m^5.0.0[22m" from [1m@typescript-eslint/eslint-plugin[22m@[1m1.13.0[22m[2m[22m
297 error [2mnode_modules/@typescript-eslint/eslint-plugin[22m
297 error   [33mdev[39m [1m@typescript-eslint/eslint-plugin[22m@"[1m^1.12.0[22m" from the root project
297 error
297 error Fix the upstream dependency conflict, or retry
297 error this command with --force, or --legacy-peer-deps
297 error to accept an incorrect (and potentially broken) dependency resolution.
297 error
297 error See /home/juvenile_lad/.npm/eresolve-report.txt for a full report.
298 verbose exit 1

```

**Comment by iamLiquidX** [comment]
Run sudo npm install instead of npm install

**Comment by JuvenileLad** [comment]
> Run sudo npm install instead of npm install

It had no effect.

**Comment by iamLiquidX** [comment]
Use the --force as suggested in error , and try with it

sudo npm install --force ,
Also wait for admin to reply

**Comment by xingxp** [comment]
just run "node --max_old_space_size=128 ./out/index.js"
